version: '3'
services:
    app:
        build:
            context: ./docker/php_apache
            dockerfile: Dockerfile
        ports:
            - 80:80
        volumes:
            - ./:/var/www/laravel
        working_dir: /var/www/laravel
        tty: true
        networks:
            - dev
        depends_on:
            - mariadb
    mariadb:
        image: mariadb:10.3
        container_name: mariadb_laravel
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: "%"
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
            TZ: 'Asia/Tokyo'
        volumes:
            - ./docker/mariadb/data:/var/lib/mysql
            - ./docker/mariadb/my.cnf:/etc/mysql/conf.d/my.cnf
        networks:
            - dev
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}"]
            retries: 3
            timeout: 5s
    adminer:
        container_name: adminer
        image: adminer:4.8.1
        restart: always
        ports:
            - 8080:8080
        networks:
            - dev
        depends_on:
            - mariadb
networks:
    dev:
        driver: bridge
